### ISSUE TITLE
Ingress to mdm fails to communicate due to SSL issues

### ISSUE THREAD

**Issue by afogg01** [WorkloadAutomation/ibm-workload-automation-chart#2]
Good afternoon,

After configuring a Kubernetes cluster with IWS, I found that the Ingress to the mdm was not working, as the ingress was attempting to communicate with the mdm using http / plaintext.

I found the fix to this was to add an extra annotation to workload-automation-prod/charts/wa-server-prod/templates/mdm-ingress.yml : **nginx.ingress.kubernetes.io/backend-protocol: HTTPS**

The file now looks like this:

```yaml
####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if eq (.Values.server.exposeServiceType | upper )  "INGRESS" }} 
{{- include "wa.init" (list . "waserver") }}
{{ $fullName := include "wa.fullName" . }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "waMdm.ServiceName" . }}
  labels:
{{ include "wa.server.labels" . | indent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
{{- with .Values.server.exposeServiceAnnotation }}
{{ toYaml . | indent 4 }} 
{{- end }}
spec:
  tls:
    - hosts:
      {{- if .Values.server.ingress.hostname }}
       - {{ .Values.server.ingress.hostname }}
      {{- else }}  
       - {{ $fullName }}.{{ .Release.Name }}.{{ .Release.Namespace }}.mycluster.proxy
      {{- end }}    
      {{- if .Values.server.ingress.secretName }}       
      secretName: {{ .Values.server.ingress.secretName }}    
      {{- end }}         
  rules:
  {{- if .Values.server.ingress.hostname }}
  - host: {{ .Values.server.ingress.hostname }}
  {{- else }}  
  - host: {{ $fullName }}.{{ .Release.Name }}.{{ .Release.Namespace }}.mycluster.proxy
  {{- end }} 
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "waMdm.ServiceName" . }}
          servicePort: 31116
{{- end }}            
```
